---
name: Development global config Data
description:
  Configuration needed for development environment

variables:
  # confidential variables should be ENV VARS
  email: "{tavern.env_vars.TEST_EMAIL}"
  password: "{tavern.env_vars.TEST_PASSWORD}"
  host: "{tavern.env_vars.API_URL}"


