---

name: Authentication stage
description:
  Reusable test stage for authentication

stages:
  - id: login_get_token
    name: Login and acquire token
    request:
      url: "{host:s}/api/login/"
      params:
        email: "{email:s}"
        password: "{password:s}"
      method: GET
    response:
      status_code: 200
      save:
        json:
          test_token: key
